title: Holiness Fellowship
name: Holiness Fellowship
description: >-
  At the Holiness Fellowship, our focus is holiness in the Wesleyan tradition.
baseurl: ""
url: "https://holinessfellowship.github.io"

author: Matthew E. Denson
email: matthew@densons.org
facebook_username: Sequim-Holiness-Church-109701320399932

# plugins:
#   - jekyll-feed
permalink: /blog/:categories/:year/:month/:day/:title.html

markdown: kramdown

css: inline
sass:
  style: compressed


# Defaults

# Enable is_post test for posts
# Enable is_page test for pages
# Enable is_home test for home page
# Use {% if page.is_post %} etc.
defaults:
  -
    scope:
      path: ""
      layout: home
    values:
      is_home: true
  -
    scope:
      path: ""
      type: posts
    values:
      is_post: true
  -
    scope:
      path: ""
      type: pages
    values:
      is_page: true

exclude:
  - Gemfile
  - Gemfile.lock
  - docker
  - Makefile
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

